	MODULE ComDat_Param                                  

	IMPLICIT NONE
	SAVE

	INTEGER, PARAMETER :: NI	= 201
	INTEGER, PARAMETER :: NJ	= 201
	INTEGER, PARAMETER :: NK	= 121
	
	INTEGER, PARAMETER :: NDIMJ = 8
	INTEGER, PARAMETER :: NDIMK = 4
	
	INTEGER, PARAMETER :: NDIMS = 2
	INTEGER, PARAMETER :: NSWPP = 20
	
	INTEGER, PARAMETER :: IRESTART = 0
	
	INTEGER :: IPOST	= 0
	
    INTEGER :: NITER_W   = 1E6
    INTEGER :: NITER_R   = 4E4
	
	DOUBLE PRECISION ::				RTIME_MAX = 300.D0
	
	DOUBLE PRECISION, PARAMETER ::	RTIME_END =	406.D0
    
	DOUBLE PRECISION, PARAMETER :: REF_A = 6.283185307	!	REFERENCE AREA FOR CIRCULAR CYLINDER
!	DOUBLE PRECISION, PARAMETER :: REF_A = 5.340707511	!	REFERENCE AREA FOR ELLIPTIC CYLINDER A1.15 B0.85 ATTACK_ANGLE 0
!	DOUBLE PRECISION, PARAMETER :: REF_A = 7.225663103	!	REFERENCE AREA FOR ELLIPTIC CYLINDER A1.15 B0.85 ATTACK_ANGLE 90
!	DOUBLE PRECISION, PARAMETER :: REF_A = 6.271004		!	REFERENCE AREA FOR SKEWEDD CYLINDER WITH e=0.05
!	DOUBLE PRECISION, PARAMETER :: REF_A = 6.236295		!	REFERENCE AREA FOR SKEWEDD CYLINDER WITH e=0.10
!	DOUBLE PRECISION, PARAMETER :: REF_A = 6.177589		!	REFERENCE AREA FOR SKEWEDD CYLINDER WITH e=0.15
!	DOUBLE PRECISION, PARAMETER :: REF_A = 6.094993		!	REFERENCE AREA FOR SKEWEDD CYLINDER WITH e=0.20
    
    DOUBLE PRECISION, PARAMETER :: RESIMAX = 1.0D-4
    DOUBLE PRECISION, PARAMETER :: CFL_USE = 0.29D0
    
    DOUBLE PRECISION :: UIN
!	DOUBLE PRECISION, PARAMETER :: UIN		= 1.D0
	DOUBLE PRECISION, PARAMETER :: TIN		= 0.D0
    DOUBLE PRECISION, PARAMETER :: T_WALL	= 1.D0
    DOUBLE PRECISION, PARAMETER :: VEL_ROT	= 0.D0		!	ROTATING VELOCITY

    DOUBLE PRECISION :: DTIME = 2.0D-3	!2.5D-3
	DOUBLE PRECISION :: RE = 600.D0	!300.D0		! REYNOLDS NUMBER
	DOUBLE PRECISION :: PR = 0.71D0		! PRANDTLE NUMBER
	DOUBLE PRECISION :: PE = 426.D0	!213.D0		! PECLET NUMBER

	END MODULE ComDat_Param