	MODULE COMDAT_PARAM
	
	IMPLICIT NONE
	SAVE
	
	INTEGER, PARAMETER :: NI	= 81
	INTEGER, PARAMETER :: NJ	= 81
	INTEGER, PARAMETER :: NK	= 10
	
	INTEGER, PARAMETER :: NDIMJ = 8
	INTEGER, PARAMETER :: NDIMK = 4
	
	END MODULE COMDAT_PARAM