	SUBROUTINE CUBICF(A,B,C,D,ROOT)
	
	IMPLICIT NONE
	SAVE
	
	DOUBLE PRECISION, INTENT(IN) :: A,B,C,D
	DOUBLE PRECISION, INTENT(INOUT) :: ROOT(1:3)
	
	DOUBLE PRECISION :: DUM_A,DUM_B
	DOUBLE PRECISION :: DISC ! DISCRIMINANT
	
	DISC = 18.D0*A*B*C*D -4.D0*B**3*D +B**2*C**2 -4.D0*A*C**3 -27.D0*A**2*D**2
	
!	IF(DISC .GT. 0.D0) WRITE(*,*) 'THE CUBIC FUNCTION HAS THREE DISTINCT REAL ROOTS.'
!	IF(DISC .EQ. 0.D0) WRITE(*,*) 'THE CUBIC FUNCTION HAS A MULTIPLE ROOT AND ALL ITS ROOTS ARE REAL.'
	IF(DISC .LT. 0.D0) WRITE(*,*) 'THE CUBIC FUNCTION HAS ONE REAL ROOT AND TWO NONREAL COMPLEX CONJUGATE ROOTS.'
	
	DUM_A = 2.D0*B**3 -9.D0*A*B*C +27.D0*A**2*D
	DUM_B = DSQRT((DUM_A)**2-4.D0*(B**2 -3.D0*A*C)**3)
		
	ROOT(1) = -B/(3.D0*A)
	ROOT(1) = ROOT(1) -1.D0/(3.D0*A)*(0.5D0*(DUM_A + DUM_B))*(1.D0/3.D0)
	ROOT(1) = ROOT(1) -1.D0/(3.D0*A)*(0.5D0*(DUM_A - DUM_B))*(1.D0/3.D0)
	
	ROOT(2) = -B/(3.D0*A)
		
!	THE FORMULA FOR FINDING THE ROOTS OF A CUBIC FUNCTION, BASED ON CARDANO'S METHOD, IS FAIRLY COMPLICATED.

	END SUBROUTINE CUBICF