    SUBROUTINE ITER_T
    
    USE COMDAT_SHARED
    
    IMPLICIT NONE
    SAVE
    
    INCLUDE 'mpif.h'
    
	!   TRI-DIAGONAL COMPONENTS OF LINEAR MATRIX EQUATION

    AP(IS:IE,JS:JE,KS:KE) = FP	+AE(IS:IE,JS:JE,KS:KE)+AW(IS:IE,JS:JE,KS:KE)	&
								+AN(IS:IE,JS:JE,KS:KE)+AS(IS:IE,JS:JE,KS:KE)	&
								+AT(IS:IE,JS:JE,KS:KE)+AB(IS:IE,JS:JE,KS:KE)

	!   TDMA solver
    
    CALL DIF_DIAGONAL(T,DD) ! DIAGONAL DIF OF U^* : TREATED AS EXPLICIT

	!	SUMMATION OF EXPLICIT COMPONENTS
	
    SU(IS1:IE1,JS1:JE1,KS1:KE1)	= FP*T(IS1:IE1,JS1:JE1,KS1:KE1)									&
                -3.D0*PE*ADV (IS1:IE1,JS1:JE1,KS1:KE1) +1.D0*PE*ADV_NM1(IS1:IE1,JS1:JE1,KS1:KE1)&
		        +1.D0*PE*DIFT(IS1:IE1,JS1:JE1,KS1:KE1)											&
		        +DD(IS1:IE1,JS1:JE1,KS1:KE1)

    CALL BCT
	
	CALL LISOLV(IS1,JS1,KS1,IE,JE,KE,T) ! WITHOUT OVER-RELAXATION
	
	CALL MPI_X(T)
	
    END SUBROUTINE ITER_T