    SUBROUTINE ITER_U(IN,INM,INA,INB,INC,IND)
    
    USE COMDAT_SHARED
    
    IMPLICIT NONE
    SAVE
	
	INCLUDE 'mpif.h'
    
	INTEGER :: status(MPI_STATUS_SIZE)
	
	!   DEFINE ARGUMENT VARIABLES
	
	DOUBLE PRECISION, INTENT(INOUT)	:: IN (IS:IE,JS:JE,KS:KE)
	DOUBLE PRECISION, INTENT(IN)	:: INM(IS:IE,JS:JE,KS:KE)
	DOUBLE PRECISION, INTENT(IN)	:: INA(IS:IE,JS:JE,KS:KE)
	DOUBLE PRECISION, INTENT(IN)	:: INB(IS:IE,JS:JE,KS:KE)
	DOUBLE PRECISION, INTENT(IN)	:: INC(IS:IE,JS:JE,KS:KE)
	DOUBLE PRECISION, INTENT(IN)	:: IND(IS:IE,JS:JE,KS:KE)
	

	!   TRI-DIAGONAL COMPONENTS OF LINEAR MATRIX EQUATION

    AP(IS:IE,JS:JE,KS:KE) = FP	+AE(IS:IE,JS:JE,KS:KE)+AW(IS:IE,JS:JE,KS:KE)	&
								+AN(IS:IE,JS:JE,KS:KE)+AS(IS:IE,JS:JE,KS:KE)	&
								+AT(IS:IE,JS:JE,KS:KE)+AB(IS:IE,JS:JE,KS:KE)

	!   TDMA solver
    
    CALL DIF_DIAGONAL(IN,DD) ! DIAGONAL DIF OF U^* : TREATED AS EXPLICIT

	!	SUMMATION OF EXPLICIT COMPONENTS
	
	SU(IS1:IE1,JS1:JE1,KS1:KE1)	= FP*INM(IS1:IE1,JS1:JE1,KS1:KE1)							&
				-3.D0*RE*INA(IS1:IE1,JS1:JE1,KS1:KE1) +1.D0*RE*INB(IS1:IE1,JS1:JE1,KS1:KE1)	&
				+1.D0*RE*INC(IS1:IE1,JS1:JE1,KS1:KE1) +2.D0*RE*IND(IS1:IE1,JS1:JE1,KS1:KE1)	&
				+DD(IS1:IE1,JS1:JE1,KS1:KE1)

    CALL BCU(IN,INM)

	CALL LISOLV(IS1,JS1,KS1,IE,JE,KE,IN) ! WITHOUT OVER-RELAXATION
	
	CALL MPI_X(IN)
	
    END SUBROUTINE ITER_U