	PROGRAM MAIN
	
!	USE COMDAT_SHARED
	
	IMPLICIT NONE
	SAVE

	INTEGER, PARAMETER :: NI	= 241
	INTEGER, PARAMETER :: NJ	= 201
	INTEGER, PARAMETER :: NK	= 121
		
	INTEGER :: I,J,K
	INTEGER :: ALLOC_ERR
	
	CHARACTER(15) :: FILENAME
    CHARACTER(14) :: FILENAME2
    CHARACTER(11) :: CONTOUR
	
	DOUBLE PRECISION ::	DUM,DUM_A,DUM_B,DUM_C,DUM_D
	DOUBLE PRECISION :: L1,L2,L3
	DOUBLE PRECISION :: D_N
    DOUBLE PRECISION :: TH1
    DOUBLE PRECISION :: PI
    
	DOUBLE PRECISION, ALLOCATABLE :: X(:,:,:) ,Y(:,:,:),Z(:,:,:)
	DOUBLE PRECISION, ALLOCATABLE :: XG(:,:,:),YG(:,:,:),ZG(:,:,:)
    
	DOUBLE PRECISION, ALLOCATABLE :: RD1(:,:,:)
	DOUBLE PRECISION, ALLOCATABLE :: RD2(:,:,:)
	DOUBLE PRECISION, ALLOCATABLE :: TE1(:,:,:)
	DOUBLE PRECISION, ALLOCATABLE :: TE2(:,:,:)
	
	DOUBLE PRECISION, ALLOCATABLE :: THETA(:,:,:)
	DOUBLE PRECISION, ALLOCATABLE :: RADIUS(:,:,:)
	
	DOUBLE PRECISION, ALLOCATABLE :: V1(:,:,:)
	DOUBLE PRECISION, ALLOCATABLE :: V2(:,:,:)
	DOUBLE PRECISION, ALLOCATABLE :: V3(:,:,:)
	DOUBLE PRECISION, ALLOCATABLE :: V4(:,:,:)
	DOUBLE PRECISION, ALLOCATABLE :: V5(:,:,:)
	DOUBLE PRECISION, ALLOCATABLE :: V6(:,:,:)
	DOUBLE PRECISION, ALLOCATABLE :: V7(:,:,:)
	
	DOUBLE PRECISION, ALLOCATABLE :: CPA(:,:,:)
	
	DOUBLE PRECISION, ALLOCATABLE :: AREA1(:,:,:)
	DOUBLE PRECISION, ALLOCATABLE :: AREA2(:,:,:)







	ALLOCATE(X(0:NI,0:NJ,0:NK),STAT=ALLOC_ERR)
	ALLOCATE(Y(0:NI,0:NJ,0:NK),STAT=ALLOC_ERR)
	ALLOCATE(Z(0:NI,0:NJ,0:NK),STAT=ALLOC_ERR)

	ALLOCATE(XG(1:NI,1:NJ,1:NK),STAT=ALLOC_ERR)
	ALLOCATE(YG(1:NI,1:NJ,1:NK),STAT=ALLOC_ERR)
	ALLOCATE(ZG(1:NI,1:NJ,1:NK),STAT=ALLOC_ERR)
	
	ALLOCATE(RD1(1,1:NJ-1,1:NK-1),STAT=ALLOC_ERR)
	ALLOCATE(RD2(1,1:NJ-1,1:NK-1),STAT=ALLOC_ERR)
	ALLOCATE(TE1(1,1:NJ-1,1:NK-1),STAT=ALLOC_ERR)
	ALLOCATE(TE2(1,1:NJ-1,1:NK-1),STAT=ALLOC_ERR)
	
	ALLOCATE(RADIUS(1,1:NJ-1,1:NK-1),STAT=ALLOC_ERR)
	ALLOCATE(THETA(1,1:NJ-1,1:NK-1),STAT=ALLOC_ERR)
	
	ALLOCATE(V1(1,1:NJ-1,1:NK-1),STAT=ALLOC_ERR)
	ALLOCATE(V2(1,1:NJ-1,1:NK-1),STAT=ALLOC_ERR)
	ALLOCATE(V3(1,1:NJ-1,1:NK-1),STAT=ALLOC_ERR)
	ALLOCATE(V4(1,1:NJ-1,1:NK-1),STAT=ALLOC_ERR)
	ALLOCATE(V5(1,1:NJ-1,1:NK-1),STAT=ALLOC_ERR)
	ALLOCATE(V6(1,1:NJ-1,1:NK-1),STAT=ALLOC_ERR)
	ALLOCATE(V7(1,1:NJ-1,1:NK-1),STAT=ALLOC_ERR)
	
	ALLOCATE(AREA1(1,1:NJ-1,1:NK-1),STAT=ALLOC_ERR)
	ALLOCATE(AREA2(1,1:NJ-1,1:NK-1),STAT=ALLOC_ERR)
	
	
	
	
	PI=4.0D0*DATAN(1.0D0)
	
		
	OPEN(UNIT=10,FILE='instant_surface.dat',STATUS='OLD')
	READ(10,*) !CHARACTER1
	READ(10,*) !CHARACTER2
	READ(10,*) !CHARACTER3
	READ(10,*) !CHARACTER4
	READ(10,*) !CHARACTER5
	READ(10,*) !CHARACTER6
	READ(10,*) !CHARACTER7
	DO K=1,NK
	DO J=1,NJ
	I=1
		READ(10,*) X(I,J,K),Y(I,J,K),Z(I,J,K),V1(I,J,K),V2(I,J,K),V3(I,J,K),V4(I,J,K),V5(I,J,K),V6(I,J,K)
	ENDDO
	ENDDO
	CLOSE(10)
	
	DO K=1,NK
	DO J=1,NJ
	I=1
		RADIUS(I,J,K) = DSQRT(X(I,J,K)**2+Y(I,J,K)**2)
	ENDDO
    ENDDO

	
	DO K=1,NK
	DO J=1,NJ
	I=1
      THETA(I,J,K) = DATAN(Y(I,J,K)/X(I,J,K))
 	  IF     (THETA(I,J,K).GE.0.0D0.AND.DASIN(Y(I,J,K)/RADIUS(I,J,K)).GT.0.0D0) THEN
		THETA(I,J,K) = THETA(I,J,K)
 	  
	  ELSEIF (THETA(I,J,K).LT.0.0D0.AND.DASIN(Y(I,J,K)/RADIUS(I,J,K)).GT.0.0D0) THEN
		THETA(I,J,K) = PI+THETA(I,J,K)

 	  ELSEIF (THETA(I,J,K).GE.0.0D0.AND.DASIN(Y(I,J,K)/RADIUS(I,J,K)).LE.0.0D0) THEN
		THETA(I,J,K) = PI+THETA(I,J,K)

	  ELSEIF (THETA(I,J,K).LT.0.0D0.AND.DASIN(Y(I,J,K)/RADIUS(I,J,K)).LT.0.0D0) THEN
		THETA(I,J,K) = 2.0D0*PI+THETA(I,J,K)
	  ENDIF
	ENDDO
	ENDDO

	
	

	OPEN(UNIT=100,FILE='INSTANT_SURF.dat',STATUS='UNKNOWN')
	WRITE(100,*) 'TITLE="SURFACE DATA."'
	WRITE(100,*) 'variables="x","y","z","Theta","P","U","V","W","T","M"'
	WRITE(100,45) 1,NJ-1,NK-1
45	FORMAT(TR1,'ZONE T="POST", I=',I6,', J=',I6,', K=',I6)
	DO K=1,NK-1
	DO J=1,NJ-1
	I=1
		WRITE(100,46) X(I,J,K),Y(I,J,K),Z(I,J,K),THETA(I,J,K),V1(I,J,K),V2(I,J,K),V3(I,J,K),V4(I,J,K),V5(I,J,K),V6(I,J,K)
46		FORMAT(TR1,D16.9,TR1,D16.9,TR1,D16.9,TR1,D16.9,TR1,D16.9,TR1,D16.9,TR1,D16.9,TR1,D16.9,TR1,D16.9,TR1,D16.9)
	ENDDO
	ENDDO
	CLOSE(100)
	
	
	
	END PROGRAM MAIN