    SUBROUTINE ITER_U(IN,INM,INA,INB,INC,IND)
    
    USE COMDAT_SHARED
    
    IMPLICIT NONE
    SAVE
	
	INCLUDE 'mpif.h'
    
	INTEGER :: status(MPI_STATUS_SIZE)
	
	!   DEFINE ARGUMENT VARIABLES
	
	DOUBLE PRECISION, INTENT(INOUT)	:: IN (IS:IE,JS:JE,KS:KE)
	DOUBLE PRECISION, INTENT(IN)	:: INM(IS:IE,JS:JE,KS:KE)
	DOUBLE PRECISION, INTENT(IN)	:: INA(IS:IE,JS:JE,KS:KE)
	DOUBLE PRECISION, INTENT(IN)	:: INB(IS:IE,JS:JE,KS:KE)
	DOUBLE PRECISION, INTENT(IN)	:: INC(IS:IE,JS:JE,KS:KE)
	DOUBLE PRECISION, INTENT(IN)	:: IND(IS:IE,JS:JE,KS:KE)
	

	!   TRI-DIAGONAL COMPONENTS OF LINEAR MATRIX EQUATION

    AP(IS1:IE1,JS1:JE1,KS1:KE1) = FP	+DE(IS1:IE1,JS1:JE1,KS1:KE1)+DW(IS1:IE1,JS1:JE1,KS1:KE1)	&
										+DN(IS1:IE1,JS1:JE1,KS1:KE1)+DS(IS1:IE1,JS1:JE1,KS1:KE1)	&
										+DT(IS1:IE1,JS1:JE1,KS1:KE1)+DB(IS1:IE1,JS1:JE1,KS1:KE1)
	
	AE(IS1:IE1,JS1:JE1,KS1:KE1) = DE(IS1:IE1,JS1:JE1,KS1:KE1)
	AW(IS1:IE1,JS1:JE1,KS1:KE1) = DW(IS1:IE1,JS1:JE1,KS1:KE1)
	AN(IS1:IE1,JS1:JE1,KS1:KE1) = DN(IS1:IE1,JS1:JE1,KS1:KE1)
	AS(IS1:IE1,JS1:JE1,KS1:KE1) = DS(IS1:IE1,JS1:JE1,KS1:KE1)
	AT(IS1:IE1,JS1:JE1,KS1:KE1) = DT(IS1:IE1,JS1:JE1,KS1:KE1)
	AB(IS1:IE1,JS1:JE1,KS1:KE1) = DB(IS1:IE1,JS1:JE1,KS1:KE1)
	
	!   TDMA solver
    
    CALL DIF_DIAGONAL(IN,DD) ! DIAGONAL DIF OF U^* : TREATED AS EXPLICIT

	!	SUMMATION OF EXPLICIT COMPONENTS
	
	SU(IS1:IE1,JS1:JE1,KS1:KE1)	= FP*INM(IS1:IE1,JS1:JE1,KS1:KE1)							&
				-3.D0*RE*INA(IS1:IE1,JS1:JE1,KS1:KE1) +1.D0*RE*INB(IS1:IE1,JS1:JE1,KS1:KE1)	&
				+1.D0*RE*INC(IS1:IE1,JS1:JE1,KS1:KE1) +2.D0*RE*IND(IS1:IE1,JS1:JE1,KS1:KE1)	&
				+DD(IS1:IE1,JS1:JE1,KS1:KE1)

    CALL BCU(IN,INM)

	CALL LISOLV(IS,JS,KS,IE,JE,KE,IN) ! WITHOUT OVER-RELAXATION
	
    END SUBROUTINE ITER_U