	PROGRAM MAIN
	
	IMPLICIT NONE
	SAVE
	
	INTEGER :: K
	INTEGER :: N
	INTEGER :: NMAX
	INTEGER :: ALLOC_ERR
	
	DOUBLE PRECISION :: PI
	
	DOUBLE PRECISION, ALLOCATABLE :: VAL(:)
	DOUBLE PRECISION, ALLOCATABLE :: TIME(:)
	DOUBLE PRECISION, ALLOCATABLE :: FREQ(:)
	DOUBLE PRECISION, ALLOCATABLE :: REAL_X(:)
	DOUBLE PRECISION, ALLOCATABLE :: IMAG_X(:)
	DOUBLE PRECISION, ALLOCATABLE :: MAG_X(:)
	
!=======================================================
	WRITE(*,*) ''
	WRITE(*,*) 'INPUT FILE = "FFT.DAT"'
	WRITE(*,*) ''
	WRITE(*,*) 'INPUT NUMBER OF SAMPLING DATA'
	READ (*,*)  NMAX
	
	ALLOCATE(VAL(0:NMAX-1),STAT=ALLOC_ERR)
	ALLOCATE(TIME(0:NMAX-1),STAT=ALLOC_ERR)
	ALLOCATE(FREQ(0:NMAX-1),STAT=ALLOC_ERR)
	ALLOCATE(REAL_X(0:NMAX-1),STAT=ALLOC_ERR)
	ALLOCATE(IMAG_X(0:NMAX-1),STAT=ALLOC_ERR)
	ALLOCATE(MAG_X(0:NMAX-1),STAT=ALLOC_ERR)
	PI=4.0D0*DATAN(1.0D0)
	
	OPEN(UNIT=10,FILE='FFT.DAT',STATUS='OLD')
	DO N=0,NMAX-1
	READ(10,*) VAL(N)
	ENDDO
	CLOSE(10)
	
	DO K=1,(NMAX-1)/2
		
		WRITE(*,*) K
		
		REAL_X(K)=0.D0
		IMAG_X(K)=0.D0
		
		DO N=0,NMAX-1
			REAL_X(K) = REAL_X(K)+VAL(N)*DCOS(2.D0*PI*N*K/(NMAX+1))
			IMAG_X(K) = IMAG_X(K)-VAL(N)*DSIN(2.D0*PI*N*K/(NMAX+1))
		ENDDO
	
	ENDDO
	
	OPEN(UNIT=11,FILE='FFT_RESULTS.DAT',STATUS='UNKNOWN')
	DO K=1,(NMAX-1)/2
	FREQ(K) = DBLE(K)/DBLE(NMAX)*2.5D-3	!FREQ(K) = 2.D0*PI*DBLE(K)/DBLE(NMAX)
	MAG_X(K)= DSQRT(REAL_X(K)**2+IMAG_X(K)**2)
	WRITE(11,*) FREQ(K),MAG_X(K)
	ENDDO
	
	END PROGRAM MAIN