    SUBROUTINE BC_PLI

    USE COMDAT_SHARED

	IMPLICIT NONE
	SAVE
	
	INCLUDE 'mpif.h'
	
	INTEGER :: status(MPI_STATUS_SIZE)
	
    DUM_3D=PLI

!-------------------------------------------
!   PERIODIC WALL OF BOUNDARY
!-------------------------------------------
	CALL MPI_X(PLI)
	
	IF(RANK.EQ.0)		CALL MPI_ISEND(PLI(IS,JS,KS1),1,APLN,NPRC-1,1,COMM_NEW,ISEND1,ERR)
	
	IF(RANK.EQ.NPRC-1)	CALL MPI_ISEND(PLI(IS,JS,KE1),1,APLN,0,1,COMM_NEW,ISEND2,ERR)

	IF(RANK.EQ.NPRC-1)	CALL MPI_IRECV(PLI(IS,JS,KE) ,1,APLN,0,1,COMM_NEW,IRECV1,ERR)
		
	IF(RANK.EQ.0)		CALL MPI_IRECV(PLI(IS,JS,KS) ,1,APLN,NPRC-1,1,COMM_NEW,IRECV2,ERR)
	
	CALL MPI_WAIT(ISEND1,STATUS,ERR)
	
	CALL MPI_WAIT(ISEND2,STATUS,ERR)
	
	CALL MPI_WAIT(IRECV1,STATUS,ERR)
	
	CALL MPI_WAIT(IRECV2,STATUS,ERR)

!-----------------------------------------
!   CYLINDER SURFACE AND INLET & OUTLET
!-----------------------------------------
	I=IS
	! WALL BOUNDARY SURFACE
    !AP(I+1,JS1:JE1,KS:KE) = AP(I+1,JS1:JE1,KS:KE)-AW(I+1,JS1:JE1,KS:KE)
    AW(I+1,JS1:JE1,KS:KE) = 0.0D0
    PLI(I,JS1:JE1,KS:KE) = 1.D0/3.D0*((4.D0*PLI(I+1,JS1:JE1,KS:KE)-PLI(I+2,JS1:JE1,KS:KE))					&
                +Q12(I,JS1:JE1,KS:KE)/Q11(I,JS1:JE1,KS:KE) *0.5D0*(DUM_3D(I,JS1+1:JE1+1,KS:KE)-DUM_3D(I,JS1-1:JE1-1,KS:KE)))

    I=IE
	! OUTFLOW BOUNDARY SURFACE
    !AP(I-1,JS1:JE1,KS:KE) = AP(I-1,JS1:JE1,KS:KE)-AE(I-1,JS1:JE1,KS:KE)
    AE(I-1,JS1:JE1,KS:KE) = 0.0D0
    PLI(I,JS1:JE1,KS:KE) = 1.D0/3.D0*((4.D0*PLI(I-1,JS1:JE1,KS:KE)-PLI(I-2,JS1:JE1,KS:KE))					&
 				-Q12(I,JS1:JE1,KS:KE)/Q11(I,JS1:JE1,KS:KE) *0.5D0*(DUM_3D(I,JS1+1:JE1+1,KS:KE)-DUM_3D(I,JS1-1:JE1-1,KS:KE)))

!-------------------------------------------
!   BRANCH CUT REGION
!-------------------------------------------
    PLI(IS:IE,JS,KS:KE) = PLI(IS:IE,JE1,KS:KE)

	PLI(IS:IE,JE,KS:KE) = PLI(IS:IE,JS1,KS:KE)
	
    END SUBROUTINE BC_PLI