	SUBROUTINE FIND_ROOT(A,B,C,D,ROOT)
	
	IMPLICIT NONE
	SAVE
	
	DOUBLE PRECISION, INTENT(IN) :: A,B,C,D
	DOUBLE PRECISION, INTENT(INOUT) :: ROOT(1:3)
	
	DOUBLE PRECISION :: Q,R,RHO,PHI
	DOUBLE PRECISION :: DISC ! DISCRIMINANT
	
	Q = (3.D0*A*C-B**2)/(9.D0*A**2)
	R = (9.D0*A*B*C-27.D0*A**2*D-2.D0*B**3)/(54.D0*A**3)
	
	DISC = Q**3 + R**2
	
!	IF(DISC .LT. 0.D0) WRITE(*,*) 'THE CUBIC FUNCTION HAS THREE DISTINCT REAL ROOTS.'
	IF(DISC .EQ. 0.D0) WRITE(*,*) 'THE CUBIC FUNCTION HAS A MULTIPLE ROOT AND ALL ITS ROOTS ARE REAL.'
	IF(DISC .GT. 0.D0) WRITE(*,*) 'THE CUBIC FUNCTION HAS ONE REAL ROOT AND TWO NONREAL COMPLEX CONJUGATE ROOTS.'
	
	RHO = DSQRT(-Q**3)
	PHI = DACOS(R/RHO)
		
	ROOT(1) = -B/(3.D0*A) +2.D0*RHO**(1.D0/3.D0)*DCOS(PHI/3.D0)
	ROOT(2) = -B/(3.D0*A) -RHO**(1.D0/3.D0)*DCOS(PHI/3.D0) +DSQRT(3.D0)*RHO**(1.D0/3.D0)*DSIN(PHI/3.D0)
	ROOT(3) = -B/(3.D0*A) -RHO**(1.D0/3.D0)*DCOS(PHI/3.D0) -DSQRT(3.D0)*RHO**(1.D0/3.D0)*DSIN(PHI/3.D0)
	
	END SUBROUTINE FIND_ROOT