	SUBROUTINE DEFINE
	
	USE COMDAT_SHARED
	
	IMPLICIT NONE
	SAVE
!------------------------------------------------------------------        
!	PARALLEL PROGRAM USING MPI(MASSAGE PASSING INTERFACE)

    INCLUDE 'mpif.h'
    
	CALL MPI_INIT(ERR)
	
    CALL MPI_COMM_RANK(MPI_COMM_WORLD,RANK,ERR)
    
	CALL MPI_COMM_SIZE(MPI_COMM_WORLD,NPRC,ERR)

	CALL MPI_CART_CREATE(MPI_COMM_WORLD,1,NPRC,PERIODS,REORDER,COMM_NEW,ERR)

	CALL MPI_COMM_RANK(COMM_NEW,RANK,ERR)
	
	CALL MPI_CART_COORDS(COMM_NEW,RANK,1,COORDS,ERR)
	
	CALL MPI_CART_SHIFT(COMM_NEW,0,1,IPRV,INXT,ERR)
	
	! A ROW DATA IN THE CELL-CENTER BASED COMPUTATIONAL DOMAIN
	
	CALL MPI_TYPE_CONTIGUOUS(IE-IS+1,MPI_DOUBLE_PRECISION,AROW,ERR)	
	
	CALL MPI_TYPE_COMMIT(AROW,ERR)
	
	! A COLUMN DATA IN THE CELL-CENTER BASED COMPUTATIONAL DOMAIN
	
	CALL MPI_TYPE_VECTOR(JE-JS+1,1,IE-IS+1,MPI_DOUBLE_PRECISION,CLMN,ERR)
	
	CALL MPI_TYPE_COMMIT(CLMN,ERR)
	

	PI=4.0D0*DATAN(1.0D0)
	
	NIM1 = NI-1
	NJM1 = NJ-1
	NKM1 = NK-1
	
	NUM_GRID=(NI+1)*(NJ+1)*(NK-2)

	! DEFINE THE INTERVAL PARAMETER
	IS =0
	IS1=IS +1
	IE =NI
	IE1=IE -1
	
	JS =0
	JS1=JS +1
	JE =NJ
	JE1=JE -1
	
	KS =0
	KS1=KS +1
	KE =NK
	KE1=KE -1

		INTA = (NK+1)/NPRC
		INTB = MOD(NK+1,NPRC)
	KS =RANK*INTA+MIN(RANK,INTB)
	KE =KS+INTA-1
		IF(INTB.GT.RANK) KE=KE+1
	KS = KS-1	! BOUNDARY BETWEEN PROCESSORS
	KE = KE+1
		IF(RANK.EQ.0)		KS=KS+1
		IF(RANK.EQ.NPRC-1)	KE=KE-1
	KS1=KS +1
	KE1=KE -1

	INXT = RANK +1
	IPRV = RANK -1
	IF(RANK.EQ.0)		IPRV = MPI_PROC_NULL
	IF(RANK.EQ.NPRC-1)	INXT = MPI_PROC_NULL

    WRITE(*,62) RANK,NPRC,KS,KE
!	WRITE(*,71) RANK,NPRC,IPRV,INXT
62	FORMAT(TR1,'PROCESSOR',I3,TR1,'OF',I3,TR6,' : KMIN =',I4,', KMAX =',I4)
71	FORMAT(TR1,'PROCESSOR',I3,TR1,'OF',I3,TR6,' : PREV =',I4,', NEXT =',I4)
	
!------------------------------------------------------------------
!	READ INPUT PARAMETER AND NONDIMENSIONAL NUMBER
	IF(RANK.EQ.0) THEN
	PRINT *, ""
    PRINT *, "Input restart parameter. (0=start : 1=restart)"
    READ (*,*)  IRESTART
		IF(IRESTART.EQ.0) THEN
	    WRITE(*,*) 'Input Reynolds Number.'
        RE =100		!READ (*,*)  RE
        WRITE(*,*) 'Input Prandtl  Number.'
        PR =0.7		!READ (*,*)  PR
        WRITE(*,*) 'Input time step size.'
        DTIME =1.0d-3	!READ (*,*)  DTIME
		ELSE
        RTIME_MAX = RTIME_MAX * 2.D0
		ENDIF
	PE = RE*PR
    ENDIF
!------------------------------------------------------------------

    CALL MPI_BCAST(IRESTART,1,MPI_INTEGER,0,MPI_COMM_WORLD,ERR)
	
    CALL MPI_BCAST(RE,1,MPI_DOUBLE_PRECISION,0,MPI_COMM_WORLD,ERR)
    
    CALL MPI_BCAST(PR,1,MPI_DOUBLE_PRECISION,0,MPI_COMM_WORLD,ERR)
    
    CALL MPI_BCAST(PE,1,MPI_DOUBLE_PRECISION,0,MPI_COMM_WORLD,ERR)
    
	CALL MPI_BCAST(DTIME,1,MPI_DOUBLE_PRECISION,0,MPI_COMM_WORLD,ERR)
	
	CALL MPI_BCAST(RTIME_MAX,1,MPI_DOUBLE_PRECISION,0,MPI_COMM_WORLD,ERR)

!	ALLOCATE THE VARIABLES IN THE PARALLEL PRECESS

	ALLOCATE(U_N(IS:IE,JS:JE,KS:KE),STAT=ALLOC_ERR)
	ALLOCATE(V_N(IS:IE,JS:JE,KS:KE),STAT=ALLOC_ERR)
	ALLOCATE(W_N(IS:IE,JS:JE,KS:KE),STAT=ALLOC_ERR)
	ALLOCATE(T_N(IS:IE,JS:JE,KS:KE),STAT=ALLOC_ERR)
	
	ALLOCATE(PLI(IS:IE,JS:JE,KS:KE),STAT=ALLOC_ERR)
	
	ALLOCATE(DUM_3D(IS:IE,JS:JE,KS:KE),STAT=ALLOC_ERR)
	
	ALLOCATE(U1(IS:IE,JS:JE,KS:KE),STAT=ALLOC_ERR)
	ALLOCATE(U2(IS:IE,JS:JE,KS:KE),STAT=ALLOC_ERR)
	ALLOCATE(U3(IS:IE,JS:JE,KS:KE),STAT=ALLOC_ERR)
	
	ALLOCATE(UE(IS:IE,JS:JE,KS:KE),STAT=ALLOC_ERR)
	ALLOCATE(UW(IS:IE,JS:JE,KS:KE),STAT=ALLOC_ERR)
	ALLOCATE(VN(IS:IE,JS:JE,KS:KE),STAT=ALLOC_ERR)
	ALLOCATE(VS(IS:IE,JS:JE,KS:KE),STAT=ALLOC_ERR)
	ALLOCATE(WT(IS:IE,JS:JE,KS:KE),STAT=ALLOC_ERR)
	ALLOCATE(WB(IS:IE,JS:JE,KS:KE),STAT=ALLOC_ERR)
	
	ALLOCATE(NLX(IS:IE,JS:JE,KS:KE),STAT=ALLOC_ERR)
	ALLOCATE(NLY(IS:IE,JS:JE,KS:KE),STAT=ALLOC_ERR)
	ALLOCATE(NLZ(IS:IE,JS:JE,KS:KE),STAT=ALLOC_ERR)
	ALLOCATE(NLX_NM1(IS:IE,JS:JE,KS:KE),STAT=ALLOC_ERR)
	ALLOCATE(NLY_NM1(IS:IE,JS:JE,KS:KE),STAT=ALLOC_ERR)
	ALLOCATE(NLZ_NM1(IS:IE,JS:JE,KS:KE),STAT=ALLOC_ERR)
	
	ALLOCATE(ADV(IS:IE,JS:JE,KS:KE),STAT=ALLOC_ERR)
	ALLOCATE(ADV_NM1(IS:IE,JS:JE,KS:KE),STAT=ALLOC_ERR)
	
	ALLOCATE(DIFX(IS:IE,JS:JE,KS:KE),STAT=ALLOC_ERR)
	ALLOCATE(DIFY(IS:IE,JS:JE,KS:KE),STAT=ALLOC_ERR)
	ALLOCATE(DIFZ(IS:IE,JS:JE,KS:KE),STAT=ALLOC_ERR)
	ALLOCATE(DIFT(IS:IE,JS:JE,KS:KE),STAT=ALLOC_ERR)
	
	ALLOCATE(S_U(IS:IE,JS:JE,KS:KE),STAT=ALLOC_ERR)
	ALLOCATE(S_V(IS:IE,JS:JE,KS:KE),STAT=ALLOC_ERR)
	ALLOCATE(S_W(IS:IE,JS:JE,KS:KE),STAT=ALLOC_ERR)
	
	ALLOCATE(AP(IS:IE,JS:JE,KS:KE),STAT=ALLOC_ERR)
	ALLOCATE(AE(IS:IE,JS:JE,KS:KE),STAT=ALLOC_ERR)
	ALLOCATE(AW(IS:IE,JS:JE,KS:KE),STAT=ALLOC_ERR)
	ALLOCATE(AN(IS:IE,JS:JE,KS:KE),STAT=ALLOC_ERR)
	ALLOCATE(AS(IS:IE,JS:JE,KS:KE),STAT=ALLOC_ERR)
	ALLOCATE(AT(IS:IE,JS:JE,KS:KE),STAT=ALLOC_ERR)
	ALLOCATE(AB(IS:IE,JS:JE,KS:KE),STAT=ALLOC_ERR)
	
	ALLOCATE(DE(IS:IE,JS:JE,KS:KE),STAT=ALLOC_ERR)
	ALLOCATE(DW(IS:IE,JS:JE,KS:KE),STAT=ALLOC_ERR)
	ALLOCATE(DN(IS:IE,JS:JE,KS:KE),STAT=ALLOC_ERR)
	ALLOCATE(DS(IS:IE,JS:JE,KS:KE),STAT=ALLOC_ERR)
	ALLOCATE(DT(IS:IE,JS:JE,KS:KE),STAT=ALLOC_ERR)
	ALLOCATE(DB(IS:IE,JS:JE,KS:KE),STAT=ALLOC_ERR)
	ALLOCATE(DD(IS:IE,JS:JE,KS:KE),STAT=ALLOC_ERR)
	
	ALLOCATE(SU(IS:IE,JS:JE,KS:KE),STAT=ALLOC_ERR)
	
	ALLOCATE(RADIUS(IS:IE,JS:JE,KS:KE),STAT=ALLOC_ERR)
	ALLOCATE(THETA(IS:IE,JS:JE,KS:KE),STAT=ALLOC_ERR)
	
	ALLOCATE(DJAC(IS:IE,JS:JE,KS:KE),STAT=ALLOC_ERR)
	
	ALLOCATE(XXI(IS:IE,JS:JE,KS:KE),STAT=ALLOC_ERR)
	ALLOCATE(YXI(IS:IE,JS:JE,KS:KE),STAT=ALLOC_ERR)
	ALLOCATE(ZXI(IS:IE,JS:JE,KS:KE),STAT=ALLOC_ERR)
	ALLOCATE(XET(IS:IE,JS:JE,KS:KE),STAT=ALLOC_ERR)
	ALLOCATE(YET(IS:IE,JS:JE,KS:KE),STAT=ALLOC_ERR)
	ALLOCATE(ZET(IS:IE,JS:JE,KS:KE),STAT=ALLOC_ERR)
	ALLOCATE(XZT(IS:IE,JS:JE,KS:KE),STAT=ALLOC_ERR)
	ALLOCATE(YZT(IS:IE,JS:JE,KS:KE),STAT=ALLOC_ERR)
	ALLOCATE(ZZT(IS:IE,JS:JE,KS:KE),STAT=ALLOC_ERR)
	
	ALLOCATE(XIX(IS:IE,JS:JE,KS:KE),STAT=ALLOC_ERR)
	ALLOCATE(XIY(IS:IE,JS:JE,KS:KE),STAT=ALLOC_ERR)
	ALLOCATE(XIZ(IS:IE,JS:JE,KS:KE),STAT=ALLOC_ERR)
	ALLOCATE(ETX(IS:IE,JS:JE,KS:KE),STAT=ALLOC_ERR)
	ALLOCATE(ETY(IS:IE,JS:JE,KS:KE),STAT=ALLOC_ERR)
	ALLOCATE(ETZ(IS:IE,JS:JE,KS:KE),STAT=ALLOC_ERR)
	ALLOCATE(ZTX(IS:IE,JS:JE,KS:KE),STAT=ALLOC_ERR)
	ALLOCATE(ZTY(IS:IE,JS:JE,KS:KE),STAT=ALLOC_ERR)
	ALLOCATE(ZTZ(IS:IE,JS:JE,KS:KE),STAT=ALLOC_ERR)
	
	ALLOCATE(Q11(IS:IE,JS:JE,KS:KE),STAT=ALLOC_ERR)
	ALLOCATE(Q12(IS:IE,JS:JE,KS:KE),STAT=ALLOC_ERR)
	ALLOCATE(Q13(IS:IE,JS:JE,KS:KE),STAT=ALLOC_ERR)
	ALLOCATE(Q21(IS:IE,JS:JE,KS:KE),STAT=ALLOC_ERR)
	ALLOCATE(Q22(IS:IE,JS:JE,KS:KE),STAT=ALLOC_ERR)
	ALLOCATE(Q23(IS:IE,JS:JE,KS:KE),STAT=ALLOC_ERR)
	ALLOCATE(Q31(IS:IE,JS:JE,KS:KE),STAT=ALLOC_ERR)
	ALLOCATE(Q32(IS:IE,JS:JE,KS:KE),STAT=ALLOC_ERR)
	ALLOCATE(Q33(IS:IE,JS:JE,KS:KE),STAT=ALLOC_ERR)
    
	ALLOCATE(DUDN(IS1,JS1:JE1,KS1:KE1),STAT=ALLOC_ERR)
	ALLOCATE(DTDN(IS1,JS1:JE1,KS1:KE1),STAT=ALLOC_ERR)
	ALLOCATE(AREA(IS1,JS1:JE1,KS1:KE1),STAT=ALLOC_ERR)
	
	END SUBROUTINE DEFINE