    SUBROUTINE ITER_U(IN,INM,INA,INB,INC,IND)
    
    USE COMDAT_SHARED
    
    IMPLICIT NONE
    SAVE
    
    INCLUDE 'mpif.h'
    
    INTEGER :: status(MPI_STATUS_SIZE)
!---------------------------------------------------------------------------
!   DEFINE ARGUMENT VARIABLES
	DOUBLE PRECISION, INTENT(INOUT)	:: IN (IS:IE,JS:JE,KS:KE)
	DOUBLE PRECISION, INTENT(IN)	:: INM(IS:IE,JS:JE,KS:KE)
	DOUBLE PRECISION, INTENT(IN)	:: INA(IS:IE,JS:JE,KS:KE)
	DOUBLE PRECISION, INTENT(IN)	:: INB(IS:IE,JS:JE,KS:KE)
	DOUBLE PRECISION, INTENT(IN)	:: INC(IS:IE,JS:JE,KS:KE)
	DOUBLE PRECISION, INTENT(IN)	:: IND(IS:IE,JS:JE,KS:KE)
	
!---------------------------------------------------------------------------
!   TRI-DIAGONAL COMPONENTS OF LINEAR MATRIX EQUATION
!   AT THE CELL CENTER : P
!   THE NEIGHBOR CELLS : E,W,N,S,T,B
!   THE EXPLICIT TERMS : Su
    AP(IS:IE,JS:JE,KS:KE) = FP												&
							+DE(IS:IE,JS:JE,KS:KE)+DW(IS:IE,JS:JE,KS:KE)	&
							+DN(IS:IE,JS:JE,KS:KE)+DS(IS:IE,JS:JE,KS:KE)	&
							+DT(IS:IE,JS:JE,KS:KE)+DB(IS:IE,JS:JE,KS:KE)
							
    AE(IS:IE,JS:JE,KS:KE) = DE(IS:IE,JS:JE,KS:KE)
	AW(IS:IE,JS:JE,KS:KE) = DW(IS:IE,JS:JE,KS:KE)
	AN(IS:IE,JS:JE,KS:KE) = DN(IS:IE,JS:JE,KS:KE)
	AS(IS:IE,JS:JE,KS:KE) = DS(IS:IE,JS:JE,KS:KE)
	AT(IS:IE,JS:JE,KS:KE) = DT(IS:IE,JS:JE,KS:KE)
	AB(IS:IE,JS:JE,KS:KE) = DB(IS:IE,JS:JE,KS:KE)
	SU(IS:IE,JS:JE,KS:KE) = 0
!---------------------------------------------------------------------------

!---------------------------------------------------------------------------
!   TDMA solver
    CALL DIF_DIAGONAL(IN,DD) ! DIAGONAL DIF OF U^* : TREATED AS EXPLICIT

!--- SUMMATION OF EXPLICIT COMPONENTS --------------------------------------
	SU(IS1:IE1,JS1:JE1,KS1:KE1)	= FP*IN(IS1:IE1,JS1:JE1,KS1:KE1)							&
				-3.D0*RE*INA(IS1:IE1,JS1:JE1,KS1:KE1) +1.D0*RE*INB(IS1:IE1,JS1:JE1,KS1:KE1)	&
				+1.D0*RE*INC(IS1:IE1,JS1:JE1,KS1:KE1) +2.D0*RE*IND(IS1:IE1,JS1:JE1,KS1:KE1)	&
				+DD(IS1:IE1,JS1:JE1,KS1:KE1)

!--- LINE GAUSS-GEIDEL ITERATION METHOD ------------------------------------
    CALL BCU(IN,INM)

	CALL LISOLV(IS1,JS1,KS1,IE,JE,KE,IN) ! WITHOUT OVER-RELAXATION

!	MPI : COLUMN-DIRECTION BLOCK DIVISION

	DO J=JS,JE
	
	CALL MPI_ISEND(IN(IS,J,KE1),IE-IS+1,MPI_DOUBLE_PRECISION,INXT,1,MPI_COMM_WORLD,ISEND1,ERR)
	
	CALL MPI_ISEND(IN(IS,J,KS1),IE-IS+1,MPI_DOUBLE_PRECISION,IPRV,2,MPI_COMM_WORLD,ISEND2,ERR)
	
	CALL MPI_IRECV(IN(IS,J,KS) ,IE-IS+1,MPI_DOUBLE_PRECISION,IPRV,1,MPI_COMM_WORLD,IRECV1,ERR)
	
	CALL MPI_IRECV(IN(IS,J,KE) ,IE-IS+1,MPI_DOUBLE_PRECISION,INXT,2,MPI_COMM_WORLD,IRECV2,ERR)
	
	CALL MPI_WAIT(ISEND1,STATUS,ERR)
	
	CALL MPI_WAIT(ISEND2,STATUS,ERR)
	
	CALL MPI_WAIT(IRECV1,STATUS,ERR)
	
	CALL MPI_WAIT(IRECV2,STATUS,ERR)

	ENDDO

    END SUBROUTINE ITER_U