	SUBROUTINE MPI_X(INOUT)
	
	USE COMDAT_SHARED
	
	IMPLICIT NONE
	SAVE
	
	INCLUDE 'mpif.h'
	
	INTEGER :: STATUS(MPI_STATUS_SIZE)
	
	DOUBLE PRECISION, INTENT(INOUT) :: INOUT(IS:IE,JS:JE,KS:KE)
	
	! MPI : COLUMN-DIRECTION BLOCK DIVISION

!	DO J=JS,JE
!	
!	CALL MPI_ISEND(INOUT(IS,J,KE1),1,AROW,INXT,1,MPI_COMM_WORLD,ISEND1,ERR)
!	
!	CALL MPI_ISEND(INOUT(IS,J,KS1),1,AROW,IPRV,1,MPI_COMM_WORLD,ISEND2,ERR)
!	
!	CALL MPI_IRECV(INOUT(IS,J,KS) ,1,AROW,IPRV,1,MPI_COMM_WORLD,IRECV1,ERR)
!	
!	CALL MPI_IRECV(INOUT(IS,J,KE) ,1,AROW,INXT,1,MPI_COMM_WORLD,IRECV2,ERR)
!
!	CALL MPI_WAIT(ISEND1,STATUS,ERR)
!	
!	CALL MPI_WAIT(ISEND2,STATUS,ERR)
!	
!	CALL MPI_WAIT(IRECV1,STATUS,ERR)
!	
!	CALL MPI_WAIT(IRECV2,STATUS,ERR)
!	
!	ENDDO
	
	DO J=JS,JE
	
	DO I=IS,IE
	
	CALL MPI_ISEND(INOUT(I,J,KE1),1,MPI_DOUBLE_PRECISION,INXT,1,MPI_COMM_WORLD,ISEND1,ERR)
	
	CALL MPI_ISEND(INOUT(I,J,KS1),1,MPI_DOUBLE_PRECISION,IPRV,1,MPI_COMM_WORLD,ISEND2,ERR)
	
	CALL MPI_IRECV(INOUT(I,J,KS) ,1,MPI_DOUBLE_PRECISION,IPRV,1,MPI_COMM_WORLD,IRECV1,ERR)
	
	CALL MPI_IRECV(INOUT(I,J,KE) ,1,MPI_DOUBLE_PRECISION,INXT,1,MPI_COMM_WORLD,IRECV2,ERR)

	CALL MPI_WAIT(ISEND1,STATUS,ERR)
	
	CALL MPI_WAIT(ISEND2,STATUS,ERR)
	
	CALL MPI_WAIT(IRECV1,STATUS,ERR)
	
	CALL MPI_WAIT(IRECV2,STATUS,ERR)
	
	ENDDO
	
	ENDDO
	
!	MPI : COLUMN-DIRECTION BLOCK DIVISION 2
	
!	DO J=JS,JE
!
!	CALL MPI_SENDRECV (IN(0,J,KE1), 1, AROW, INXT, 1, IN(0,J,KS), 1, AROW, IPRV, TAG3, MPI_COMM_WORLD, STATUS, ERR)
!	
!	CALL MPI_SENDRECV (IN(0,J,KS1), 1, AROW, IPRV, 1, IN(0,J,KE), 1, AROW, INXT, TAG4, MPI_COMM_WORLD, STATUS, ERR)
!	
!	ENDDO
	

	END SUBROUTINE MPI_X