	PROGRAM MAIN
	
!	USE COMDAT_SHARED
	
	IMPLICIT NONE
	SAVE

	INTEGER, PARAMETER :: NI	= 241
	INTEGER, PARAMETER :: NJ	= 201
	INTEGER, PARAMETER :: NK	= 121
		
	INTEGER :: I,J,K
	INTEGER :: ALLOC_ERR
	
	CHARACTER(15) :: FILENAME
    CHARACTER(14) :: FILENAME2
    CHARACTER(11) :: CONTOUR
	
	DOUBLE PRECISION ::	DUM,DUM_A,DUM_B,DUM_C,DUM_D
	DOUBLE PRECISION :: L1,L2,L3
	DOUBLE PRECISION :: D_N
    DOUBLE PRECISION :: TH1
    DOUBLE PRECISION :: PI
    
	DOUBLE PRECISION, ALLOCATABLE :: X(:,:,:) ,Y(:,:,:),Z(:,:,:)
	DOUBLE PRECISION, ALLOCATABLE :: XG(:,:,:),YG(:,:,:),ZG(:,:,:)
    
	DOUBLE PRECISION, ALLOCATABLE :: RD1(:,:,:)
	DOUBLE PRECISION, ALLOCATABLE :: RD2(:,:,:)
	DOUBLE PRECISION, ALLOCATABLE :: TE1(:,:,:)
	DOUBLE PRECISION, ALLOCATABLE :: TE2(:,:,:)
	
	DOUBLE PRECISION, ALLOCATABLE :: THETA(:,:,:)	
	DOUBLE PRECISION, ALLOCATABLE :: CF(:,:,:)
	DOUBLE PRECISION, ALLOCATABLE :: NU(:,:,:)
	DOUBLE PRECISION, ALLOCATABLE :: CP(:,:,:)
	
	DOUBLE PRECISION, ALLOCATABLE :: CPA(:,:,:)
	
	DOUBLE PRECISION, ALLOCATABLE :: AREA1(:,:,:)
	DOUBLE PRECISION, ALLOCATABLE :: AREA2(:,:,:)







	ALLOCATE(X(0:NI,0:NJ,0:NK),STAT=ALLOC_ERR)
	ALLOCATE(Y(0:NI,0:NJ,0:NK),STAT=ALLOC_ERR)
	ALLOCATE(Z(0:NI,0:NJ,0:NK),STAT=ALLOC_ERR)

	ALLOCATE(XG(1:NI,1:NJ,1:NK),STAT=ALLOC_ERR)
	ALLOCATE(YG(1:NI,1:NJ,1:NK),STAT=ALLOC_ERR)
	ALLOCATE(ZG(1:NI,1:NJ,1:NK),STAT=ALLOC_ERR)
	
	ALLOCATE(RD1(1,1:NJ-1,1:NK-1),STAT=ALLOC_ERR)
	ALLOCATE(RD2(1,1:NJ-1,1:NK-1),STAT=ALLOC_ERR)
	ALLOCATE(TE1(1,1:NJ-1,1:NK-1),STAT=ALLOC_ERR)
	ALLOCATE(TE2(1,1:NJ-1,1:NK-1),STAT=ALLOC_ERR)
	
	ALLOCATE(THETA(1,1:NJ-1,1:NK-1),STAT=ALLOC_ERR)
	ALLOCATE(CF(1,1:NJ-1,1:NK-1),STAT=ALLOC_ERR)
	ALLOCATE(NU(1,1:NJ-1,1:NK-1),STAT=ALLOC_ERR)
	ALLOCATE(CP(1,1:NJ-1,1:NK-1),STAT=ALLOC_ERR)
	ALLOCATE(CPA(1,1:NJ-1,1:NK-1),STAT=ALLOC_ERR)
	
	ALLOCATE(AREA1(1,1:NJ-1,1:NK-1),STAT=ALLOC_ERR)
	ALLOCATE(AREA2(1,1:NJ-1,1:NK-1),STAT=ALLOC_ERR)
	
	PI=4.0D0*DATAN(1.0D0)
	
	FILENAME = '000X000X000.DAT'
	
	WRITE(FILENAME(1:3),'(I3.3)') INT(NI)
	
	WRITE(FILENAME(5:7),'(I3.3)') INT(NJ)
	
	WRITE(FILENAME(9:11),'(I3.3)') INT(NK)

	OPEN(UNIT=10,FILE=FILENAME,STATUS='OLD')
	DO K=1,NK
	DO J=1,NJ
	DO I=1,NI
		READ(10,*) XG(I,J,K),YG(I,J,K),ZG(I,J,K)
	ENDDO
	ENDDO
	ENDDO
	CLOSE(10)
	
	DO K=1,NK-1
    DO J=1,NJ-1
    I=1
    L1 =DSQRT((XG(I,J+1,K)-XG(I,J,K))**2+(YG(I,J+1,K)-YG(I,J,K))**2+(ZG(I,J+1,K)-ZG(I,J,K))**2)
	L2 =DSQRT((XG(I,J,K+1)-XG(I,J,K))**2+(YG(I,J,K+1)-YG(I,J,K))**2+(ZG(I,J,K+1)-ZG(I,J,K))**2)
	L3 =DSQRT((XG(I,J+1,K)-XG(I,J,K+1))**2+(YG(I,J+1,K)-YG(I,J,K+1))**2+(ZG(I,J+1,K)-ZG(I,J,K+1))**2)
	TH1=DACOS((L3**2-L2**2-L1**2)/(-2.D0*L1*L2))
	AREA1(I,J,K) = 0.5D0*L1*L2*DSIN(TH1)
    
    L1 =DSQRT((XG(I,J+1,K+1)-XG(I,J+1,K))**2+(YG(I,J+1,K+1)-YG(I,J+1,K))**2+(ZG(I,J+1,K+1)-ZG(I,J+1,K))**2)
	L2 =DSQRT((XG(I,J+1,K+1)-XG(I,J,K+1))**2+(YG(I,J+1,K+1)-YG(I,J,K+1))**2+(ZG(I,J+1,K+1)-ZG(I,J,K+1))**2)
!	L3 =DSQRT((XG(I,J+1,K)-XG(I,J,K+1))**2+(YG(I,J+1,K)-YG(I,J,K+1))**2+(ZG(I,J+1,K)-ZG(I,J,K+1))**2)
	TH1=DACOS((L3**2-L2**2-L1**2)/(-2.D0*L1*L2))
	AREA2(I,J,K) = 0.5D0*L1*L2*DSIN(TH1)
	ENDDO
	ENDDO
	
	
	
	
	OPEN(UNIT=10,FILE='Surf_Coef.dat',STATUS='OLD')
	READ(10,*) !CHARACTER1
	READ(10,*) !CHARACTER2
	READ(10,*) !CHARACTER3
	DO K=1,NK-1
	DO J=1,NJ-1
	I=1
		READ(10,*) X(I,J,K),Y(I,J,K),Z(I,J,K),THETA(I,J,K),CF(I,J,K),CP(I,J,K),NU(I,J,K)
	ENDDO
	ENDDO
	CLOSE(10)
	
	
	
	
	
	
	
	DO K=1,NK-1
	DO J=1,NJ-1
	I=1
	! (A,B,C) : VECTOR, NORMAL VECTOR OF THE DISCRETIZED CYLINDER SURFACE
	DUM_A = YG(I,J,K)*(ZG(I,J+1,K)-ZG(I,J,K+1))+YG(I,J+1,K)*(ZG(I,J,K+1)-ZG(I,J,K))+YG(I,J,K+1)*(ZG(I,J,K)-ZG(I,J+1,K))
	DUM_B = ZG(I,J,K)*(XG(I,J+1,K)-XG(I,J,K+1))+ZG(I,J+1,K)*(XG(I,J,K+1)-XG(I,J,K))+ZG(I,J,K+1)*(XG(I,J,K)-XG(I,J+1,K))
	DUM_C = XG(I,J,K)*(YG(I,J+1,K)-YG(I,J,K+1))+XG(I,J+1,K)*(YG(I,J,K+1)-YG(I,J,K))+XG(I,J,K+1)*(YG(I,J,K)-YG(I,J+1,K))
	! -D : SCALAR, LENGTH OF THE NORMAL VECTOR
	DUM_D = XG(I,J,K)*(YG(I,J+1,K)*ZG(I,J,K+1)-YG(I,J,K+1)*ZG(I,J+1,K))+XG(I,J+1,K)*(YG(I,J,K+1)*ZG(I,J,K)-YG(I,J,K)*ZG(I,J,K+1))+XG(I,J,K+1)*(YG(I,J,K)*ZG(I,J+1,K)-YG(I,J+1,K)*ZG(I,J,K))
	DUM_D = -1.D0*DUM_D
	
	DUM = DSQRT(DUM_A**2+DUM_B**2+DUM_C**2)
	
	CPA(I,J,K) = -CP(I,J,K)*DUM_A/DUM *AREA1(I,J,K)/(AREA1(I,J,K)+AREA2(I,J,K))
	!CPA(I,J,K) = -CP(I,J,K)*DUM_B/DUM *AREA1(I,J,K)/(AREA1(I,J,K)+AREA2(I,J,K))
	ENDDO
	ENDDO
	
	DO K=1,NK-1
	DO J=1,NJ-1
	I=1
	! (A,B,C) : NORMAL VECTOR OF THE DISCRETIZED CYLINDER SURFACE
	DUM_A = YG(I,J+1,K+1)*(ZG(I,J,K+1)-ZG(I,J,K))+YG(I,J,K+1)*(ZG(I,J,K)-ZG(I,J+1,K+1))+YG(I,J,K)*(ZG(I,J+1,K+1)-ZG(I,J,K+1))
	DUM_B = ZG(I,J+1,K+1)*(XG(I,J,K+1)-XG(I,J,K))+ZG(I,J,K+1)*(XG(I,J,K)-XG(I,J+1,K+1))+ZG(I,J,K)*(XG(I,J+1,K+1)-XG(I,J,K+1))
	DUM_C = XG(I,J+1,K+1)*(YG(I,J,K+1)-YG(I,J,K))+XG(I,J,K+1)*(YG(I,J,K)-YG(I,J+1,K+1))+XG(I,J,K)*(YG(I,J+1,K+1)-YG(I,J,K+1))
	! D : LENGTH OF THE NORMAL VECTOR
	DUM_D = XG(I,J+1,K+1)*(YG(I,J,K+1)*ZG(I,J,K)-YG(I,J,K)*ZG(I,J,K+1))+XG(I,J,K+1)*(YG(I,J,K)*ZG(I,J+1,K+1)-YG(I,J+1,K+1)*ZG(I,J,K))+XG(I,J,K)*(YG(I,J+1,K+1)*ZG(I,J,K+1)-YG(I,J,K+1)*ZG(I,J+1,K+1))
	DUM_D = -1.D0*DUM_D
	
	DUM = DSQRT(DUM_A**2+DUM_B**2+DUM_C**2)
	
	CPA(I,J,K) = CPA(I,J,K) - CP(I,J,K)*DUM_A/DUM *AREA2(I,J,K)/(AREA1(I,J,K)+AREA2(I,J,K))
	!CPA(I,J,K) = CPA(I,J,K) - CP(I,J,K)*DUM_B/DUM *AREA2(I,J,K)/(AREA1(I,J,K)+AREA2(I,J,K))
	ENDDO
	ENDDO
	
	
	
	OPEN(UNIT=100,FILE='Cpa.dat',STATUS='UNKNOWN')
	WRITE(100,*) 'TITLE="SURFACE COEF."'
	WRITE(100,*) 'variables="x","y","z","Theta","Cp*a"'
	WRITE(100,45) 1,NJ-1,NK-1
45	FORMAT(TR1,'ZONE T="POST", I=',I6,', J=',I6,', K=',I6)
	DO K=1,NK-1
	DO J=1,NJ-1
	I=1
		WRITE(100,46) X(I,J,K),Y(I,J,K),Z(I,J,K),THETA(I,J,K),CPA(I,J,K)
46		FORMAT(TR1,D16.9,TR1,D16.9,TR1,D16.9,TR1,D16.9,TR1,D16.9)
	ENDDO
	ENDDO
	CLOSE(100)
	
	
	
	END PROGRAM MAIN