	MODULE COMDAT_SHARED
	
	IMPLICIT NONE
	SAVE
	
	INTEGER, PARAMETER :: NPRC	= 32
	INTEGER, PARAMETER :: NDIMJ = 8
	INTEGER, PARAMETER :: NDIMK = 4
	
	INTEGER, PARAMETER :: NI	= 241
	INTEGER, PARAMETER :: NJ	= 201
	INTEGER, PARAMETER :: NK	= 121
	
	INTEGER :: ANS1,ANS2,ANS3,ANS4,ANS5,NFRAME1,NFRAME2
	INTEGER :: RANK,INTA,INTB,L,M,N,I,J,K
	
	INTEGER :: IS(0:NPRC-1),IE(0:NPRC-1)
	INTEGER :: JS(0:NPRC-1),JE(0:NPRC-1)
	INTEGER :: KS(0:NPRC-1),KE(0:NPRC-1)
	
	CHARACTER(11) :: CONTOUR
	CHARACTER(15) :: FILENAME
	CHARACTER(17) :: FILENAME2
	
	DOUBLE PRECISION :: DUM
	DOUBLE PRECISION :: TIME
	
	DOUBLE PRECISION :: X(0:NI,0:NJ,0:NK),Y(0:NI,0:NJ,0:NK),Z(0:NI,0:NJ,0:NK)
	
	DOUBLE PRECISION :: V1(0:NI,0:NJ,0:NK)
	DOUBLE PRECISION :: V2(0:NI,0:NJ,0:NK)
	DOUBLE PRECISION :: V3(0:NI,0:NJ,0:NK)
	DOUBLE PRECISION :: V4(0:NI,0:NJ,0:NK)
	DOUBLE PRECISION :: V5(0:NI,0:NJ,0:NK)
	
	END MODULE COMDAT_SHARED