	SUBROUTINE DEFINE
	
	USE COMDAT_SHARED
	
	IMPLICIT NONE
	SAVE
	
	DO RANK=0,NPRC-1
	
	IS(RANK)=0
	IE(RANK)=NI
	
	INTA = (NJ+1+(NDIMJ-1)*2)/NDIMJ
	INTB = MOD(NJ+1+(NDIMJ-1)*2,NDIMJ)

	JS(RANK) = RANK/NDIMK * (INTA-2)
	JE(RANK) = JS(RANK) + (INTA-1)
	
	DO N=1,NDIMJ-1
		IF(NDIMJ-RANK/NDIMK.LE.INTB) JE(RANK)=JE(RANK)+1
		IF(NDIMJ-RANK/NDIMK.LT.INTB) JS(RANK)=JS(RANK)+1
		INTB=INTB-1
	ENDDO
	
	INTA = (NK+1+(NDIMK-1)*2)/NDIMK
	INTB = MOD(NK+1+(NDIMK-1)*2,NDIMK)

	KS(RANK) = MOD(RANK,NDIMK) * (INTA-2)
	KE(RANK) = KS(RANK) + (INTA-1)
	
	DO N=1,NDIMK-1
		IF(NDIMK-MOD(RANK,NDIMK).LE.INTB) KE(RANK)=KE(RANK)+1
		IF(NDIMK-MOD(RANK,NDIMK).LT.INTB) KS(RANK)=KS(RANK)+1
		INTB=INTB-1
	ENDDO
	
	WRITE(*,10) RANK,JS(RANK),JE(RANK),KS(RANK),KE(RANK)
10	FORMAT(TR1,'PROCESSOR',I3,TR4,': JMIN =',I4,', JMAX =',I4,', KMIN =',I4,', KMAX =',I4)
	
	ENDDO	! RANK-LOOP
	
	WRITE(*,*) ''
	
	END SUBROUTINE DEFINE