	PROGRAM MAIN
	
	USE COMDAT_SHARED
	
	IMPLICIT NONE
	SAVE
	
	CALL DEFINE
	
	WRITE(*,*) 'PVT_0000_00.PLT (YES:1,NO:0)'
	READ (*,*) ANS1
	IF(ANS1.EQ.1) THEN
		WRITE(*,*) 'INPUT NFRAME'
		READ (*,*) NFRAME1
	ENDIF
	
	WRITE(*,*) 'VOR_0000_00.PLT (YES:1,NO:0)'
	READ (*,*) ANS2
	IF(ANS2.EQ.1) THEN
		WRITE(*,*) 'INPUT NFRAME'
		READ (*,*) NFRAME2
	ENDIF
	
	WRITE(*,*) 'Avrg_OO.PLT (YES:1,NO:0)'
	READ (*,*) ANS3
	
	WRITE(*,*) 'Urms_OO.PLT (YES:1,NO:0)'
	READ (*,*) ANS4
	
	WRITE(*,*) 'Surf_OO.PLT (YES:1,NO:0)'
	READ (*,*) ANS5
	
	IF(ANS1.EQ.1) CALL ROUTINE1
	
	IF(ANS2.EQ.1) CALL ROUTINE2
	
	IF(ANS3.EQ.1) CALL ROUTINE3
	
	IF(ANS4.EQ.1) CALL ROUTINE4
	
	IF(ANS5.EQ.1) CALL ROUTINE5
	
	STOP

	END PROGRAM MAIN