	SUBROUTINE ROUTINE4
	
	USE COMDAT_SHARED
	
	IMPLICIT NONE
	SAVE

	!	RMS FIELD
		
	DO RANK=0,NPRC-1

	CONTOUR = 'Urms_OO.PLT'
	
	WRITE(CONTOUR(6:7),'(I2.2)') INT(RANK)
	
	OPEN(UNIT=100,FILE=CONTOUR,STATUS='OLD')
		READ(100,*)	!CHARACTER1
		READ(100,*) !CHARACTER2
		READ(100,*) !CHARACTER3
		DO K=KS(RANK)+1,KE(RANK)
		DO J=JS(RANK)+1,JE(RANK)
		DO I=IS(RANK)+1,IE(RANK)
			READ(100,*) X(I,J,K),Y(I,J,K),Z(I,J,K),V1(I,J,K),V2(I,J,K),V3(I,J,K)
		ENDDO
		ENDDO
		ENDDO
	CLOSE(100)

	ENDDO
	
	OPEN(UNIT=100,FILE='RMS_field.dat',STATUS='UNKNOWN')
	WRITE(100,*) 'TITLE="Averaged field"'
	WRITE(100,*) 'variables=x,y,z,u_rms,v_rms,w_rms'
	WRITE(100,41) NI,NJ,NK
41	FORMAT(TR1,'ZONE T="POST", I=',I6,', J=',I6,', K=',I6)
	DO K=1,NK
	DO J=1,NJ
	DO I=1,NI
		WRITE(100,42) X(I,J,K),Y(I,J,K),Z(I,J,K),V1(I,J,K),V2(I,J,K),V3(I,J,K)
42		FORMAT(TR1,D16.9,TR1,D16.9,TR1,D16.9,TR1,D16.9,TR1,D16.9,TR1,D16.9)
	ENDDO
	ENDDO
	ENDDO
	CLOSE(100)

	END SUBROUTINE ROUTINE4