	SUBROUTINE MPI_X(INOUT)
	
	USE COMDAT_SHARED
	
	IMPLICIT NONE
	SAVE
	
	INCLUDE 'mpif.h'
	
	INTEGER :: STATUS(MPI_STATUS_SIZE)
	
	DOUBLE PRECISION, INTENT(INOUT) :: INOUT(IS:IE,JS:JE,KS:KE)
	
	!	MPI : J-DIRECTION BLOCK DIVISION

!	CALL MPI_SENDRECV(INOUT(IS,JE1,KS),1,JPLN,NBR_N,0,INOUT(IS,JS,KS),1,JPLN,NBR_S,0,NMCW,STATUS,ERR)
!
!	CALL MPI_SENDRECV(INOUT(IS,JS1,KS),1,JPLN,NBR_S,1,INOUT(IS,JE,KS),1,JPLN,NBR_N,1,NMCW,STATUS,ERR)

!	CALL MPI_SENDRECV(INOUT(:,JE1,KS:KE),(IE-IS+1)*(KE-KS+1),MPI_DOUBLE_PRECISION,NBR_N,0,	&
!			INOUT(:,JS,KS:KE),(IE-IS+1)*(KE-KS+1),MPI_DOUBLE_PRECISION,NBR_S,0,NMCW,STATUS,ERR)
!			
!	CALL MPI_SENDRECV(INOUT(:,JS1,KS:KE),(IE-IS+1)*(KE-KS+1),MPI_DOUBLE_PRECISION,NBR_S,1,	&
!			INOUT(:,JE,KS:KE),(IE-IS+1)*(KE-KS+1),MPI_DOUBLE_PRECISION,NBR_N,1,NMCW,STATUS,ERR)
	
	DO K=KS,KE
	CALL MPI_SENDRECV(INOUT(:,JE1,K),IE-IS+1,MPI_DOUBLE_PRECISION,NBR_N,0,	&
			INOUT(:,JS,K),IE-IS+1,MPI_DOUBLE_PRECISION,NBR_S,0,NMCW,STATUS,ERR)
			
	CALL MPI_SENDRECV(INOUT(:,JS1,K),IE-IS+1,MPI_DOUBLE_PRECISION,NBR_S,1,	&
			INOUT(:,JE,K),IE-IS+1,MPI_DOUBLE_PRECISION,NBR_N,1,NMCW,STATUS,ERR)
	ENDDO

	
	!	MPI : K-DIRECTION BLOCK DIVISION
	
!	CALL MPI_SENDRECV(INOUT(IS,JS,KE1),1,KPLN,NBR_T,3,INOUT(IS,JS,KS),1,KPLN,NBR_B,3,NMCW,STATUS,ERR)
!	
!	CALL MPI_SENDRECV(INOUT(IS,JS,KS1),1,KPLN,NBR_B,4,INOUT(IS,JS,KE),1,KPLN,NBR_T,4,NMCW,STATUS,ERR)

!	CALL MPI_SENDRECV(INOUT(:,JS:JE,KE1),(IE-IS+1)*(JE-JS+1),MPI_DOUBLE_PRECISION,NBR_T,3,	&
!			INOUT(:,JS:JE,KS),(IE-IS+1)*(JE-JS+1),MPI_DOUBLE_PRECISION,NBR_B,3,NMCW,STATUS,ERR)
!	
!	CALL MPI_SENDRECV(INOUT(:,JS:JE,KS1),(IE-IS+1)*(JE-JS+1),MPI_DOUBLE_PRECISION,NBR_B,4,	&
!			INOUT(:,JS:JE,KE),(IE-IS+1)*(JE-JS+1),MPI_DOUBLE_PRECISION,NBR_T,4,NMCW,STATUS,ERR)

	DO J=JS,JE
	CALL MPI_SENDRECV(INOUT(:,J,KE1),IE-IS+1,MPI_DOUBLE_PRECISION,NBR_T,3,	&
			INOUT(:,J,KS),IE-IS+1,MPI_DOUBLE_PRECISION,NBR_B,3,NMCW,STATUS,ERR)
	
	CALL MPI_SENDRECV(INOUT(:,J,KS1),IE-IS+1,MPI_DOUBLE_PRECISION,NBR_B,4,	&
			INOUT(:,J,KE),IE-IS+1,MPI_DOUBLE_PRECISION,NBR_T,4,NMCW,STATUS,ERR)
	ENDDO
	
	END SUBROUTINE MPI_X