	SUBROUTINE MPI_X(INOUT)
	
	USE COMDAT_SHARED
	
	IMPLICIT NONE
	SAVE
	
	INCLUDE 'mpif.h'
	
	INTEGER :: STATUS(MPI_STATUS_SIZE)
	
	DOUBLE PRECISION, INTENT(INOUT) :: INOUT(IS:IE,JS:JE,KS:KE)
	
	! MPI : COLUMN-DIRECTION BLOCK DIVISION

	CALL MPI_ISEND(INOUT(IS,JS,KE1),1,APLN,INXT,1,MPI_COMM_WORLD,ISEND1,ERR)
	
	CALL MPI_ISEND(INOUT(IS,JS,KS1),1,APLN,IPRV,1,MPI_COMM_WORLD,ISEND2,ERR)
	
	CALL MPI_IRECV(INOUT(IS,JS,KS) ,1,APLN,IPRV,1,MPI_COMM_WORLD,IRECV1,ERR)
	
	CALL MPI_IRECV(INOUT(IS,JS,KE) ,1,APLN,INXT,1,MPI_COMM_WORLD,IRECV2,ERR)

	CALL MPI_WAIT(ISEND1,STATUS,ERR)
	
	CALL MPI_WAIT(ISEND2,STATUS,ERR)
	
	CALL MPI_WAIT(IRECV1,STATUS,ERR)
	
	CALL MPI_WAIT(IRECV2,STATUS,ERR)

!	CALL MPI_SENDRECV(INOUT(IS,JS,KE1),1,APLN,INXT,0,INOUT(IS,JS,KS) ,1,APLN,IPRV,0,MPI_COMM_WORLD,STATUS,ERR)
!	
!	CALL MPI_SENDRECV(INOUT(IS,JS,KS1),1,APLN,IPRV,2,INOUT(IS,JS,KE) ,1,APLN,INXT,2,MPI_COMM_WORLD,STATUS,ERR)

	END SUBROUTINE MPI_X