	MODULE COMDAT_SHARED

	USE COMDAT_PARAM
    
	IMPLICIT NONE
	SAVE

	!   MPI(Massage Passing Interface) VARIABLES
    INTEGER :: RANK, NPRC, ERR, NMCW 
    INTEGER :: AROW, CLMN, JPLN, KPLN
    INTEGER :: IPRV, INXT
    INTEGER :: SIZ
    INTEGER :: DIMS(0:NDIMS-1),COORDS(0:NDIMS-1)
    INTEGER :: NBR_S,NBR_N,NBR_B,NBR_T
    INTEGER :: ISEND1, ISEND2, ISEND3, ISEND4
    INTEGER :: IRECV1, IRECV2, IRECV3, IRECV4
    INTEGER, ALLOCATABLE :: DSIZ(:), DISP(:)
    
    LOGICAL :: REORDER(0:NDIMS-1)
    LOGICAL :: PERIODS(0:NDIMS-1)

	INTEGER :: I,J,K,L,M,N
	INTEGER :: NUM_GRID,NUM_WRITE
	INTEGER :: ALLOC_ERR
	INTEGER :: INTA,INTB
	
	INTEGER :: NITER
	INTEGER :: NITER_TIME
	
	INTEGER :: NIM1,NJM1,NKM1
	INTEGER :: NIM2,NJM2,NKM2
	INTEGER :: IS,JS,KS,IE,JE,KE,IS1,JS1,KS1,IE1,JE1,KE1
		
	LOGICAL :: SIGN
	
    CHARACTER(15) :: FILENAME
    CHARACTER(14) :: FILENAME2
    CHARACTER(11) :: CONTOUR
    
	DOUBLE PRECISION :: PI
	
	DOUBLE PRECISION :: RESOR,RESIP,RESIU,RESIT
	
	DOUBLE PRECISION :: CFL_MAX,CFL_LOCAL
	
	DOUBLE PRECISION :: RTIME
	DOUBLE PRECISION :: TIME_BEGIN,TIME_END
	
	DOUBLE PRECISION ::	DUM,DUM_A,DUM_B,DUM_C,DUM_D
	
	DOUBLE PRECISION :: U_F
	
	DOUBLE PRECISION :: DUDX,DUDY,DUDZ
	DOUBLE PRECISION :: DVDX,DVDY,DVDZ
	DOUBLE PRECISION :: DWDX,DWDY,DWDZ
	
	DOUBLE PRECISION, ALLOCATABLE :: U(:,:,:),V(:,:,:),W(:,:,:)
	DOUBLE PRECISION, ALLOCATABLE :: P(:,:,:)
    
    DOUBLE PRECISION, ALLOCATABLE :: UG(:,:,:),VG(:,:,:),WG(:,:,:)
	DOUBLE PRECISION, ALLOCATABLE :: PG(:,:,:)
	
	DOUBLE PRECISION, ALLOCATABLE :: VOR_X(:,:,:),VOR_Y(:,:,:),VOR_Z(:,:,:),VOR_M(:,:,:)

	!	N-TIME STEP VALUES ARE NEEDED FOR PROPER BOUNDARY VALUE
    DOUBLE PRECISION, ALLOCATABLE :: U_N(:,:,:),V_N(:,:,:),W_N(:,:,:)
	
	DOUBLE PRECISION, ALLOCATABLE :: DUM_3D(:,:,:)

	!   CONTRA-VARIENT VELOCITY
	DOUBLE PRECISION, ALLOCATABLE :: U1(:,:,:),U2(:,:,:),U3(:,:,:)
	DOUBLE PRECISION, ALLOCATABLE :: UE(:,:,:),UW(:,:,:),VN(:,:,:),VS(:,:,:),WT(:,:,:),WB(:,:,:)

	DOUBLE PRECISION, ALLOCATABLE :: NLX(:,:,:),NLY(:,:,:),NLZ(:,:,:)
	DOUBLE PRECISION, ALLOCATABLE :: NLX_NM1(:,:,:),NLY_NM1(:,:,:),NLZ_NM1(:,:,:)
	
	DOUBLE PRECISION, ALLOCATABLE :: DIFX(:,:,:),DIFY(:,:,:),DIFZ(:,:,:)
		
    DOUBLE PRECISION, ALLOCATABLE :: S_U(:,:,:),S_V(:,:,:),S_W(:,:,:)
    
	DOUBLE PRECISION, ALLOCATABLE :: AP(:,:,:)
	DOUBLE PRECISION, ALLOCATABLE :: AE(:,:,:),AW(:,:,:),AN(:,:,:),AS(:,:,:),AT(:,:,:),AB(:,:,:)
	
    DOUBLE PRECISION, ALLOCATABLE :: DE(:,:,:),DW(:,:,:),DN(:,:,:),DS(:,:,:),DT(:,:,:),DB(:,:,:)
    DOUBLE PRECISION, ALLOCATABLE :: DD(:,:,:)

	DOUBLE PRECISION, ALLOCATABLE :: SU(:,:,:)

	!   GEOMETRY
	DOUBLE PRECISION :: X_BUF,Y_BUF,Z_BUF
	
	DOUBLE PRECISION, ALLOCATABLE :: X(:,:,:) ,Y(:,:,:),Z(:,:,:)
	DOUBLE PRECISION, ALLOCATABLE :: XG(:,:,:),YG(:,:,:),ZG(:,:,:)
    
    DOUBLE PRECISION, ALLOCATABLE :: RADIUS(:,:,:)
	DOUBLE PRECISION, ALLOCATABLE :: THETA(:,:,:)
	
	!   METRIC_CENTER & METRIC_NODE
	DOUBLE PRECISION, ALLOCATABLE :: DJAC(:,:,:)
	
	DOUBLE PRECISION, ALLOCATABLE :: XXI(:,:,:),YXI(:,:,:),ZXI(:,:,:)
	DOUBLE PRECISION, ALLOCATABLE :: XET(:,:,:),YET(:,:,:),ZET(:,:,:)
    DOUBLE PRECISION, ALLOCATABLE :: XZT(:,:,:),YZT(:,:,:),ZZT(:,:,:)
    
	DOUBLE PRECISION, ALLOCATABLE :: XIX(:,:,:),XIY(:,:,:),XIZ(:,:,:)
	DOUBLE PRECISION, ALLOCATABLE :: ETX(:,:,:),ETY(:,:,:),ETZ(:,:,:)
	DOUBLE PRECISION, ALLOCATABLE :: ZTX(:,:,:),ZTY(:,:,:),ZTZ(:,:,:)

	DOUBLE PRECISION, ALLOCATABLE :: Q11(:,:,:),Q12(:,:,:),Q13(:,:,:)
	DOUBLE PRECISION, ALLOCATABLE :: Q21(:,:,:),Q22(:,:,:),Q23(:,:,:)
    DOUBLE PRECISION, ALLOCATABLE :: Q31(:,:,:),Q32(:,:,:),Q33(:,:,:)
	
	!   SURFACE_AREA,DUDN
	DOUBLE PRECISION :: DUDN
	DOUBLE PRECISION :: DTDN
	DOUBLE PRECISION :: SUM_AREA
	DOUBLE PRECISION, ALLOCATABLE :: AREA1(:,:,:)	!(IS1,JS1:JE1,KS1:KE1)
	DOUBLE PRECISION, ALLOCATABLE :: AREA2(:,:,:)	!(IS1,JS1:JE1,KS1:KE1)
	!   FRICTION_DRAG_LIFT
	DOUBLE PRECISION :: T_DRAG
	DOUBLE PRECISION :: T_LIFT_Y
	DOUBLE PRECISION :: T_LIFT_Z
	!   FORM_DRAG_LIFT
	DOUBLE PRECISION :: P_DRAG
	DOUBLE PRECISION :: P_LIFT_Y
	DOUBLE PRECISION :: P_LIFT_Z
	!   CALCCOEF
	DOUBLE PRECISION :: ST
	DOUBLE PRECISION :: CD,CL
	DOUBLE PRECISION :: CD_P,CD_V,CL_P,CL_V,CPB
	!	LINE,ANGLE,DN
    DOUBLE PRECISION :: D_N
    DOUBLE PRECISION :: TH1
	DOUBLE PRECISION :: L1,L2,L3
	!	MASS BALANCE
    DOUBLE PRECISION :: DAREA
    DOUBLE PRECISION :: MASS_INLET,MASS_OUTLET
	!   POST-PROCESSING
    INTEGER :: NITER_POS
!	DOUBLE PRECISION, ALLOCATABLE :: U_TA(:,:,:)
!	DOUBLE PRECISION, ALLOCATABLE :: V_TA(:,:,:)
!	DOUBLE PRECISION, ALLOCATABLE :: W_TA(:,:,:)
!	DOUBLE PRECISION, ALLOCATABLE :: P_TA(:,:,:)
!	DOUBLE PRECISION, ALLOCATABLE :: T_TA(:,:,:)
	DOUBLE PRECISION, ALLOCATABLE :: SH_S(:,:,:)	!	TIME-AVERAGED SURFACE SHEAR STRAIN
	DOUBLE PRECISION, ALLOCATABLE :: NU_S(:,:,:)	!	TIME-AVERAGED SURFACE NUSSELT NUMBER
	DOUBLE PRECISION, ALLOCATABLE :: CP_S(:,:,:)	!	TIME-AVERAGED SURFACE PRESSURE COEF.

	!   VORTICAL STRUCTURE
	DOUBLE PRECISION :: S1(1:3,1:3),O1(1:3,1:3),S2(1:3,1:3),O2(1:3,1:3),S2O2(1:3,1:3)
		
	DOUBLE PRECISION :: LAMDA(1:3)
	DOUBLE PRECISION :: LAMDA1,LAMDA3
	DOUBLE PRECISION, ALLOCATABLE :: LAMDA2(:,:,:)
	DOUBLE PRECISION, ALLOCATABLE :: LAMDAG(:,:,:)

	!	LARGE-EDDY SIMULATION
	DOUBLE PRECISION :: LX,LY,LZ
	DOUBLE PRECISION, ALLOCATABLE	:: WID1(:,:,:),WID2(:,:,:),WID3(:,:,:)
	
	DOUBLE PRECISION, ALLOCATABLE	:: S11(:,:,:),S12(:,:,:),S13(:,:,:)
	DOUBLE PRECISION, ALLOCATABLE	:: S22(:,:,:),S23(:,:,:)				!S21(:,:,:),S22(:,:,:),S23(:,:,:)
	DOUBLE PRECISION, ALLOCATABLE	:: S33(:,:,:)							!S31(:,:,:),S32(:,:,:),S33(:,:,:)

	DOUBLE PRECISION, ALLOCATABLE	:: A11(:,:,:),A12(:,:,:),A13(:,:,:)
	DOUBLE PRECISION, ALLOCATABLE	:: A21(:,:,:),A22(:,:,:),A23(:,:,:)
	DOUBLE PRECISION, ALLOCATABLE	:: A31(:,:,:),A32(:,:,:),A33(:,:,:)
	
	DOUBLE PRECISION, ALLOCATABLE	:: S11A(:,:,:),S12A(:,:,:),S13A(:,:,:)
	DOUBLE PRECISION, ALLOCATABLE	:: S22A(:,:,:),S23A(:,:,:)				!S21A(:,:,:),S22A(:,:,:),S23A(:,:,:)
	DOUBLE PRECISION, ALLOCATABLE	:: S33A(:,:,:)							!S31A(:,:,:),S32A(:,:,:),S33A(:,:,:)
	
	DOUBLE PRECISION, ALLOCATABLE	:: A11A(:,:,:),A12A(:,:,:),A13A(:,:,:)
	DOUBLE PRECISION, ALLOCATABLE	:: A21A(:,:,:),A22A(:,:,:),A23A(:,:,:)
	DOUBLE PRECISION, ALLOCATABLE	:: A31A(:,:,:),A32A(:,:,:),A33A(:,:,:)
	
	DOUBLE PRECISION, ALLOCATABLE	:: PHIG(:,:,:),PHIA(:,:,:)

	DOUBLE PRECISION, ALLOCATABLE	:: UA(:,:,:),VA(:,:,:),WA(:,:,:)
	
	DOUBLE PRECISION, ALLOCATABLE	:: A_IJ_A_IJ(:,:,:),S_IJ_S_IJ(:,:,:)
	
	DOUBLE PRECISION, ALLOCATABLE	:: CV(:,:,:)
	DOUBLE PRECISION, ALLOCATABLE	:: EDDY_VISCOS(:,:,:)
	DOUBLE PRECISION, ALLOCATABLE	:: SGS_X(:,:,:),SGS_Y(:,:,:),SGS_Z(:,:,:)

	DOUBLE PRECISION, ALLOCATABLE	:: U_AVG(:,:,:),U_RMS(:,:,:)
	
    ENDMODULE COMDAT_SHARED