	SUBROUTINE MPI_X(IN)
	
	USE COMDAT_SHARED
	
	IMPLICIT NONE
	SAVE
	
	INCLUDE 'mpif.h'
	
	INTEGER :: STATUS(MPI_STATUS_SIZE)
	
	DOUBLE PRECISION, INTENT(IN) :: IN(IS:IE,JS:JE,KS:KE)
	
!	MPI : COLUMN-DIRECTION BLOCK DIVISION

	DO J=JS,JE
	
	DO I=IS,IE
	
	CALL MPI_ISEND(IN(I,J,KE1),1,MPI_DOUBLE_PRECISION,INXT,TAG1,MPI_COMM_WORLD,ISEND1,ERR)
	
	CALL MPI_ISEND(IN(I,J,KS1),1,MPI_DOUBLE_PRECISION,IPRV,TAG2,MPI_COMM_WORLD,ISEND2,ERR)
	
	CALL MPI_IRECV(IN(I,J,KS) ,1,MPI_DOUBLE_PRECISION,IPRV,TAG3,MPI_COMM_WORLD,IRECV1,ERR)
	
	CALL MPI_IRECV(IN(I,J,KE) ,1,MPI_DOUBLE_PRECISION,INXT,TAG4,MPI_COMM_WORLD,IRECV2,ERR)

	CALL MPI_WAIT(ISEND1,STATUS,ERR)
	
	CALL MPI_WAIT(ISEND2,STATUS,ERR)
	
	CALL MPI_WAIT(IRECV1,STATUS,ERR)
	
	CALL MPI_WAIT(IRECV2,STATUS,ERR)
	
	ENDDO
	
	ENDDO
	WRITE(*,*) RANK,'MPI_X_PASS'
!!	MPI : COLUMN-DIRECTION BLOCK DIVISION 2
!	
!	DO J=JS,JE
!	
!	DO I=IS,IE
!
!	CALL MPI_SENDRECV (IN(I,J,KE1), 1, MPI_DOUBLE_PRECISION, INXT, TAG1, IN(I,J,KE), 1, MPI_DOUBLE_PRECISION, INXT, TAG3, MPI_COMM_WORLD, STATUS, ERR)
!
!	CALL MPI_SENDRECV (IN(I,J,KS1), 1, MPI_DOUBLE_PRECISION, IPRV, TAG2, IN(I,J,KS), 1, MPI_DOUBLE_PRECISION, IPRV, TAG4, MPI_COMM_WORLD, STATUS, ERR)
!	
!	ENDDO
!	
!	ENDDO
	

	END SUBROUTINE MPI_X